apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: money
  template:
    metadata:
      labels:
        app: money
    spec:
      containers:
        - name: cont-1
          image: chandu34/zomato:zomato
          ports:
            - containerPort: 80
